//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ubiquitous.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SteamAdmin {
            get {
                return ((string)(this["SteamAdmin"]));
            }
            set {
                this["SteamAdmin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SteamBot {
            get {
                return ((string)(this["SteamBot"]));
            }
            set {
                this["SteamBot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TwitchUser {
            get {
                return ((string)(this["TwitchUser"]));
            }
            set {
                this["TwitchUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Sc2tvUser {
            get {
                return ((string)(this["Sc2tvUser"]));
            }
            set {
                this["Sc2tvUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SteamBotPassword {
            get {
                return ((string)(this["SteamBotPassword"]));
            }
            set {
                this["SteamBotPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TwitchPassword {
            get {
                return ((string)(this["TwitchPassword"]));
            }
            set {
                this["TwitchPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Sc2tvPassword {
            get {
                return ((string)(this["Sc2tvPassword"]));
            }
            set {
                this["Sc2tvPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SteamBotAccessToken {
            get {
                return ((string)(this["SteamBotAccessToken"]));
            }
            set {
                this["SteamBotAccessToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SteamAdminId {
            get {
                return ((string)(this["SteamAdminId"]));
            }
            set {
                this["SteamAdminId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool sc2tvSanitizeSmiles {
            get {
                return ((bool)(this["sc2tvSanitizeSmiles"]));
            }
            set {
                this["sc2tvSanitizeSmiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool twitchSendStatus {
            get {
                return ((bool)(this["twitchSendStatus"]));
            }
            set {
                this["twitchSendStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool twitchBitrateAlarm {
            get {
                return ((bool)(this["twitchBitrateAlarm"]));
            }
            set {
                this["twitchBitrateAlarm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string twitchBitrateCriticalValue {
            get {
                return ((string)(this["twitchBitrateCriticalValue"]));
            }
            set {
                this["twitchBitrateCriticalValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool skypeSkipGroupMessages {
            get {
                return ((bool)(this["skypeSkipGroupMessages"]));
            }
            set {
                this["skypeSkipGroupMessages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool sc2tvPersonalizedOnly {
            get {
                return ((bool)(this["sc2tvPersonalizedOnly"]));
            }
            set {
                this["sc2tvPersonalizedOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool twitchPersonalizedOnly {
            get {
                return ((bool)(this["twitchPersonalizedOnly"]));
            }
            set {
                this["twitchPersonalizedOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool skypeEnabled {
            get {
                return ((bool)(this["skypeEnabled"]));
            }
            set {
                this["skypeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool sc2tvEnabled {
            get {
                return ((bool)(this["sc2tvEnabled"]));
            }
            set {
                this["sc2tvEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool twitchEnabled {
            get {
                return ((bool)(this["twitchEnabled"]));
            }
            set {
                this["twitchEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool steamEnabled {
            get {
                return ((bool)(this["steamEnabled"]));
            }
            set {
                this["steamEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@stm")]
        public string steamChatAlias {
            get {
                return ((string)(this["steamChatAlias"]));
            }
            set {
                this["steamChatAlias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@ttv")]
        public string twitchChatAlias {
            get {
                return ((string)(this["twitchChatAlias"]));
            }
            set {
                this["twitchChatAlias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@sc2")]
        public string sc2tvChatAlias {
            get {
                return ((string)(this["sc2tvChatAlias"]));
            }
            set {
                this["sc2tvChatAlias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@sky")]
        public string skypeChatAlias {
            get {
                return ((string)(this["skypeChatAlias"]));
            }
            set {
                this["skypeChatAlias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool goodgameEnabled {
            get {
                return ((bool)(this["goodgameEnabled"]));
            }
            set {
                this["goodgameEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@gg")]
        public string goodgameChatAlias {
            get {
                return ((string)(this["goodgameChatAlias"]));
            }
            set {
                this["goodgameChatAlias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool goodgamePersonalizedOnly {
            get {
                return ((bool)(this["goodgamePersonalizedOnly"]));
            }
            set {
                this["goodgamePersonalizedOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool twitchLeaveJoinMessages {
            get {
                return ((bool)(this["twitchLeaveJoinMessages"]));
            }
            set {
                this["twitchLeaveJoinMessages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool goodgameLeaveJoinMessages {
            get {
                return ((bool)(this["goodgameLeaveJoinMessages"]));
            }
            set {
                this["goodgameLeaveJoinMessages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool goodgameSanitizeSmiles {
            get {
                return ((bool)(this["goodgameSanitizeSmiles"]));
            }
            set {
                this["goodgameSanitizeSmiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string goodgameUser {
            get {
                return ((string)(this["goodgameUser"]));
            }
            set {
                this["goodgameUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string goodgamePassword {
            get {
                return ((string)(this["goodgamePassword"]));
            }
            set {
                this["goodgamePassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool goodgameLoadHistory {
            get {
                return ((bool)(this["goodgameLoadHistory"]));
            }
            set {
                this["goodgameLoadHistory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool sc2LoadHistory {
            get {
                return ((bool)(this["sc2LoadHistory"]));
            }
            set {
                this["sc2LoadHistory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string battlelogEmail {
            get {
                return ((string)(this["battlelogEmail"]));
            }
            set {
                this["battlelogEmail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@bbl")]
        public string battlelogChatAlias {
            get {
                return ((string)(this["battlelogChatAlias"]));
            }
            set {
                this["battlelogChatAlias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string battlelogPassword {
            get {
                return ((string)(this["battlelogPassword"]));
            }
            set {
                this["battlelogPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool battlelogShowFeedEvents {
            get {
                return ((bool)(this["battlelogShowFeedEvents"]));
            }
            set {
                this["battlelogShowFeedEvents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool battlelogEnabled {
            get {
                return ((bool)(this["battlelogEnabled"]));
            }
            set {
                this["battlelogEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string battlelogNick {
            get {
                return ((string)(this["battlelogNick"]));
            }
            set {
                this["battlelogNick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@gtv")]
        public string gohaChatAlias {
            get {
                return ((string)(this["gohaChatAlias"]));
            }
            set {
                this["gohaChatAlias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GohaUser {
            get {
                return ((string)(this["GohaUser"]));
            }
            set {
                this["GohaUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GohaPassword {
            get {
                return ((string)(this["GohaPassword"]));
            }
            set {
                this["GohaPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool gohaSendStatus {
            get {
                return ((bool)(this["gohaSendStatus"]));
            }
            set {
                this["gohaSendStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool gohaPersonalizedOnly {
            get {
                return ((bool)(this["gohaPersonalizedOnly"]));
            }
            set {
                this["gohaPersonalizedOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool gohaLeaveJoinMessages {
            get {
                return ((bool)(this["gohaLeaveJoinMessages"]));
            }
            set {
                this["gohaLeaveJoinMessages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool gohaEnabled {
            get {
                return ((bool)(this["gohaEnabled"]));
            }
            set {
                this["gohaEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GohaIRCChannel {
            get {
                return ((string)(this["GohaIRCChannel"]));
            }
            set {
                this["GohaIRCChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool enableXSplitStats {
            get {
                return ((bool)(this["enableXSplitStats"]));
            }
            set {
                this["enableXSplitStats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool enableStatusServer {
            get {
                return ((bool)(this["enableStatusServer"]));
            }
            set {
                this["enableStatusServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool gohaStreamControl {
            get {
                return ((bool)(this["gohaStreamControl"]));
            }
            set {
                this["gohaStreamControl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool gohaStreamControlOnStartExit {
            get {
                return ((bool)(this["gohaStreamControlOnStartExit"]));
            }
            set {
                this["gohaStreamControlOnStartExit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool empireEnabled {
            get {
                return ((bool)(this["empireEnabled"]));
            }
            set {
                this["empireEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@etv")]
        public string empireAlias {
            get {
                return ((string)(this["empireAlias"]));
            }
            set {
                this["empireAlias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string empireUser {
            get {
                return ((string)(this["empireUser"]));
            }
            set {
                this["empireUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string empirePassword {
            get {
                return ((string)(this["empirePassword"]));
            }
            set {
                this["empirePassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool empireSendStatus {
            get {
                return ((bool)(this["empireSendStatus"]));
            }
            set {
                this["empireSendStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool empirePersonalizedOnly {
            get {
                return ((bool)(this["empirePersonalizedOnly"]));
            }
            set {
                this["empirePersonalizedOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool empireLeavJoinMessages {
            get {
                return ((bool)(this["empireLeavJoinMessages"]));
            }
            set {
                this["empireLeavJoinMessages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool empireLoadHistory {
            get {
                return ((bool)(this["empireLoadHistory"]));
            }
            set {
                this["empireLoadHistory"] = value;
            }
        }
    }
}
